### Get all contacts from 
localhost GET http://localhost:1024/contacts

### Get contact by id from localhost 
GET http://localhost:1024/contacts/662e7ef3c599b8a358ba83ab

### Get all contacts from render 
GET https://cse341-nmog.onrender.com/contacts

### Get contact by id from render 
GET https://cse341-nmog.onrender.com/contacts/662e7ef3c599b8a358ba83ab


